"""utc_datetime_availability_and_classes

Revision ID: 185140036b6f
Revises: 371cc1680c8d
Create Date: 2026-04-08 21:20:04.282848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '185140036b6f'
down_revision: Union[str, Sequence[str], None] = '371cc1680c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('teacher_timezone', sa.String(), nullable=True))
    op.add_column('classes', sa.Column('student_timezone', sa.String(), nullable=True))
    op.add_column('classes', sa.Column('notes', sa.String(), nullable=True))
    op.alter_column('classes', 'duration',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('teacher_availability_exceptions', sa.Column('reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher_availability_exceptions', 'reason')
    op.alter_column('classes', 'duration',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('classes', 'notes')
    op.drop_column('classes', 'student_timezone')
    op.drop_column('classes', 'teacher_timezone')
    # ### end Alembic commands ###
