"""escrow_model_wallets_payment_config 3

Revision ID: 1c105dfb8b6a
Revises: bfa78640c58a
Create Date: 2026-04-09 20:00:30.026880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c105dfb8b6a'
down_revision: Union[str, Sequence[str], None] = 'bfa78640c58a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paypal_enabled', sa.Boolean(), nullable=True),
    sa.Column('binance_enabled', sa.Boolean(), nullable=True),
    sa.Column('paypal_email', sa.String(), nullable=True),
    sa.Column('binance_address', sa.String(), nullable=True),
    sa.Column('binance_network', sa.String(), nullable=True),
    sa.Column('whatsapp_number', sa.String(), nullable=True),
    sa.Column('default_commission_rate', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_config_id'), 'payment_config', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_config_id'), table_name='payment_config')
    op.drop_table('payment_config')
    # ### end Alembic commands ###
