"""class_types_subjects_renewal_packages

Revision ID: 20535298714a
Revises: 1c105dfb8b6a
Create Date: 2026-04-11 17:01:41.356602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20535298714a'
down_revision: Union[str, Sequence[str], None] = '1c105dfb8b6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE classtype AS ENUM ('trial', 'regular')")
    op.execute("CREATE TYPE enrollmentstatus AS ENUM ('active', 'completed', 'cancelled', 'pending_renewal')")
    op.add_column('classes', sa.Column('class_type', sa.Enum('trial', 'regular', name='classtype'), nullable=False, server_default='regular'))
    op.add_column('classes', sa.Column('subject', sa.String(), nullable=True))
    op.alter_column('classes', 'enrollment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('enrollments', sa.Column('renewal_count', sa.Integer(), nullable=True))
    op.add_column('enrollments', sa.Column('previous_enrollment_id', sa.Integer(), nullable=True))
    op.alter_column('enrollments', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('active', 'completed', 'cancelled', 'pending_renewal', name='enrollmentstatus'),
               existing_nullable=True,
               postgresql_using='status::text::enrollmentstatus')
    op.create_foreign_key(None, 'enrollments', 'enrollments', ['previous_enrollment_id'], ['id'])
    op.add_column('packages', sa.Column('subject', sa.String(), nullable=False, server_default='Ingles'))
    op.add_column('packages', sa.Column('description', sa.String(), nullable=True))
    op.add_column('packages', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('packages_name_key'), 'packages', type_='unique')
    op.add_column('teacher_profiles', sa.Column('subjects', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher_profiles', 'subjects')
    op.create_unique_constraint(op.f('packages_name_key'), 'packages', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('packages', 'duration_minutes')
    op.drop_column('packages', 'description')
    op.drop_column('packages', 'subject')
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.alter_column('enrollments', 'status',
               existing_type=sa.Enum('active', 'completed', 'cancelled', 'pending_renewal', name='enrollmentstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.execute("DROP TYPE enrollmentstatus")
    op.drop_column('enrollments', 'previous_enrollment_id')
    op.drop_column('enrollments', 'renewal_count')
    op.alter_column('classes', 'enrollment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('classes', 'subject')
    op.drop_column('classes', 'class_type')
    op.execute("DROP TYPE classtype")
    # ### end Alembic commands ###
