"""migrate_to_utc_datetimes

Revision ID: 371cc1680c8d
Revises: 272b0b0e866e
Create Date: 2026-04-08 21:10:24.699226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '371cc1680c8d'
down_revision: Union[str, Sequence[str], None] = '272b0b0e866e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('start_time_utc', sa.DateTime(timezone=True), nullable=False))
    op.add_column('classes', sa.Column('end_time_utc', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('classes', 'end_time_teacher')
    op.drop_column('classes', 'start_time_student')
    op.drop_column('classes', 'date_student')
    op.drop_column('classes', 'end_time_student')
    op.drop_column('classes', 'start_time_teacher')
    op.drop_column('classes', 'date_teacher')
    op.add_column('teacher_availability', sa.Column('start_time_utc', sa.String(), nullable=False))
    op.add_column('teacher_availability', sa.Column('end_time_utc', sa.String(), nullable=False))
    op.alter_column('teacher_availability', 'day_of_week',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='day_of_week::integer')
    op.drop_column('teacher_availability', 'start_time')
    op.drop_column('teacher_availability', 'end_time')
    op.add_column('teacher_availability_exceptions', sa.Column('start_time_utc', sa.DateTime(timezone=True), nullable=False))
    op.add_column('teacher_availability_exceptions', sa.Column('end_time_utc', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('teacher_availability_exceptions', 'start_time')
    op.drop_column('teacher_availability_exceptions', 'end_time')
    op.drop_column('teacher_availability_exceptions', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher_availability_exceptions', sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('teacher_availability_exceptions', sa.Column('end_time', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('teacher_availability_exceptions', sa.Column('start_time', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('teacher_availability_exceptions', 'end_time_utc')
    op.drop_column('teacher_availability_exceptions', 'start_time_utc')
    op.add_column('teacher_availability', sa.Column('end_time', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('teacher_availability', sa.Column('start_time', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('teacher_availability', 'day_of_week',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('teacher_availability', 'end_time_utc')
    op.drop_column('teacher_availability', 'start_time_utc')
    op.add_column('classes', sa.Column('date_teacher', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('classes', sa.Column('start_time_teacher', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('classes', sa.Column('end_time_student', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('classes', sa.Column('date_student', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('classes', sa.Column('start_time_student', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('classes', sa.Column('end_time_teacher', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('classes', 'end_time_utc')
    op.drop_column('classes', 'start_time_utc')
    # ### end Alembic commands ###
