"""fix_user_google

Revision ID: 3add649dd988
Revises: d0de8f4382d6
Create Date: 2026-04-18 16:07:17.067537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3add649dd988'
down_revision: Union[str, Sequence[str], None] = 'd0de8f4382d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_google_calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('calendar_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_google_google_calendar_id'), 'google_google_calendar', ['id'], unique=False)
    op.drop_index(op.f('ix_google_calendar_tokens_id'), table_name='google_calendar_tokens')
    op.drop_table('google_calendar_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_calendar_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token_expiry', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('calendar_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id'], name=op.f('google_calendar_tokens_teacher_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('google_calendar_tokens_pkey')),
    sa.UniqueConstraint('teacher_id', name=op.f('google_calendar_tokens_teacher_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_google_calendar_tokens_id'), 'google_calendar_tokens', ['id'], unique=False)
    op.drop_index(op.f('ix_google_google_calendar_id'), table_name='google_google_calendar')
    op.drop_table('google_google_calendar')
    # ### end Alembic commands ###
