"""photo_db

Revision ID: 73177484dc6c
Revises: adb8565afe4f
Create Date: 2026-04-28 09:15:40.488265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73177484dc6c'
down_revision: Union[str, Sequence[str], None] = 'adb8565afe4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('profile_photo_url', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('profile_photo_public_id', sa.String(), nullable=True))
    op.add_column('teacher_profiles', sa.Column('profile_photo_url', sa.String(), nullable=True))
    op.add_column('teacher_profiles', sa.Column('profile_photo_public_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher_profiles', 'profile_photo_public_id')
    op.drop_column('teacher_profiles', 'profile_photo_url')
    op.drop_column('student_profiles', 'profile_photo_public_id')
    op.drop_column('student_profiles', 'profile_photo_url')
    # ### end Alembic commands ###
