"""bug fix package model

Revision ID: 75ea20d02ea1
Revises: c1b2c3d4e5f6
Create Date: 2026-08-12 22:32:26.600755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75ea20d02ea1'
down_revision: Union[str, Sequence[str], None] = 'c1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classes', 'used_prepaid_credit',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('enrollments', 'unlocked_credits',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('enrollments', 'prepaid_unlimited_credits',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('enrollments', 'payment_status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'unpaid'::character varying"))
    op.alter_column('enrollments', 'installments_paid',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('enrollments', 'payment_installment_status')
    op.alter_column('packages', 'allow_installments',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('packages', 'allows_installments')
    op.alter_column('payments', 'is_manual_grant',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('payments', 'installment_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('installment_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('payments', 'is_manual_grant',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('packages', sa.Column('allows_installments', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.alter_column('packages', 'allow_installments',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('enrollments', sa.Column('payment_installment_status', sa.VARCHAR(), server_default=sa.text("'unpaid'::character varying"), autoincrement=False, nullable=False))
    op.alter_column('enrollments', 'installments_paid',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('enrollments', 'payment_status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'unpaid'::character varying"))
    op.alter_column('enrollments', 'prepaid_unlimited_credits',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('enrollments', 'unlocked_credits',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('classes', 'used_prepaid_credit',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
