"""studentsJSON-teacher_profile

Revision ID: 7ad1889f2818
Revises: acd12c441b52
Create Date: 2026-07-30 20:50:50.112017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ad1889f2818'
down_revision: Union[str, Sequence[str], None] = 'acd12c441b52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher_profiles', sa.Column('students', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher_profiles', 'students')
    # ### end Alembic commands ###
