"""escrow_model_wallets_payment_config

Revision ID: 9cb82af8b89d
Revises: df4069bedca7
Create Date: 2026-04-09 19:36:52.173237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cb82af8b89d'
down_revision: Union[str, Sequence[str], None] = 'df4069bedca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('available_balance', sa.Float(), nullable=True),
    sa.Column('total_earned', sa.Float(), nullable=True),
    sa.Column('total_withdrawn', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id')
    )
    op.create_index(op.f('ix_teacher_wallets_id'), 'teacher_wallets', ['id'], unique=False)
    op.add_column('classes', sa.Column('meet_link', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('class_id', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('payment_method', sa.String(), nullable=False))
    op.add_column('payments', sa.Column('receipt_url', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('receipt_public_id', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('transaction_id', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('validated_by', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('payments', sa.Column('rejection_reason', sa.String(), nullable=True))
    op.alter_column('payments', 'enrollment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'payments', 'classes', ['class_id'], ['id'])
    op.drop_column('payments', 'stripe_payment_id')
    op.add_column('withdrawals', sa.Column('destination_method', sa.String(), nullable=True))
    op.add_column('withdrawals', sa.Column('destination_details', sa.String(), nullable=True))
    op.add_column('withdrawals', sa.Column('processed_by', sa.Integer(), nullable=True))
    op.add_column('withdrawals', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('withdrawals', sa.Column('rejection_reason', sa.String(), nullable=True))
    op.drop_column('withdrawals', 'stripe_transfer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdrawals', sa.Column('stripe_transfer_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('withdrawals', 'rejection_reason')
    op.drop_column('withdrawals', 'processed_at')
    op.drop_column('withdrawals', 'processed_by')
    op.drop_column('withdrawals', 'destination_details')
    op.drop_column('withdrawals', 'destination_method')
    op.add_column('payments', sa.Column('stripe_payment_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.alter_column('payments', 'enrollment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('payments', 'rejection_reason')
    op.drop_column('payments', 'validated_at')
    op.drop_column('payments', 'validated_by')
    op.drop_column('payments', 'transaction_id')
    op.drop_column('payments', 'receipt_public_id')
    op.drop_column('payments', 'receipt_url')
    op.drop_column('payments', 'payment_method')
    op.drop_column('payments', 'class_id')
    op.drop_column('classes', 'meet_link')
    op.drop_index(op.f('ix_teacher_wallets_id'), table_name='teacher_wallets')
    op.drop_table('teacher_wallets')
    # ### end Alembic commands ###
