"""teacher_username-student_profile

Revision ID: acd12c441b52
Revises: cfb92f567633
Create Date: 2026-07-30 20:33:05.543670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acd12c441b52'
down_revision: Union[str, Sequence[str], None] = 'cfb92f567633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('teacher_username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'teacher_username')
    # ### end Alembic commands ###
