"""google_calendar_platform_config

Revision ID: b1731ab83df4
Revises: 20535298714a
Create Date: 2026-04-11 17:42:46.516928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1731ab83df4'
down_revision: Union[str, Sequence[str], None] = '20535298714a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_calendar_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('calendar_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id')
    )
    op.create_index(op.f('ix_google_calendar_tokens_id'), 'google_calendar_tokens', ['id'], unique=False)
    op.create_table('platform_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('featured_teacher_id', sa.Integer(), nullable=True),
    sa.Column('platform_name', sa.String(), nullable=True),
    sa.Column('platform_tagline', sa.String(), nullable=True),
    sa.Column('is_single_tenant', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['featured_teacher_id'], ['teacher_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_config_id'), 'platform_config', ['id'], unique=False)
    op.add_column('classes', sa.Column('google_event_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classes', 'google_event_id')
    op.drop_index(op.f('ix_platform_config_id'), table_name='platform_config')
    op.drop_table('platform_config')
    op.drop_index(op.f('ix_google_calendar_tokens_id'), table_name='google_calendar_tokens')
    op.drop_table('google_calendar_tokens')
    # ### end Alembic commands ###
