"""escrow_model_wallets_payment_config 2

Revision ID: bfa78640c58a
Revises: 9cb82af8b89d
Create Date: 2026-04-09 19:56:35.397599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfa78640c58a'
down_revision: Union[str, Sequence[str], None] = '9cb82af8b89d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
