"""dia de la clase

Revision ID: cfb92f567633
Revises: e127fd2275af
Create Date: 2026-07-30 00:02:46.620568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfb92f567633'
down_revision: Union[str, Sequence[str], None] = 'e127fd2275af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('day_of_week', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classes', 'day_of_week')
    # ### end Alembic commands ###
