"""legacy_reviews

Revision ID: d4e6f8a0b2c4
Revises: b2c4d6e8f0a1
Create Date: 2026-09-01 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4e6f8a0b2c4'
down_revision: Union[str, Sequence[str], None] = 'c5d7e9f1a3b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('is_legacy', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('reviews', sa.Column('legacy_student_name', sa.String(), nullable=True))
    op.alter_column('reviews', 'student_id', existing_type=sa.Integer(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # OJO: si hay reseñas legacy sin student_id, esto fallará al volver
    # a poner la columna NOT NULL — hay que limpiarlas o asignarles un
    # student_id antes de bajar esta migración.
    op.alter_column('reviews', 'student_id', existing_type=sa.Integer(), nullable=False)
    op.drop_column('reviews', 'legacy_student_name')
    op.drop_column('reviews', 'is_legacy')
    # ### end Alembic commands ###
